/* tslint:disable */
/* eslint-disable */
/**
 * MailSender.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterClientAppResponse
 */
export interface RegisterClientAppResponse {
    /**
     * 
     * @type {string}
     * @memberof RegisterClientAppResponse
     */
    appId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RegisterClientAppResponse
     */
    appName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RegisterClientAppResponse
     */
    key?: string | null;
}

/**
 * Check if a given object implements the RegisterClientAppResponse interface.
 */
export function instanceOfRegisterClientAppResponse(value: object): value is RegisterClientAppResponse {
    return true;
}

export function RegisterClientAppResponseFromJSON(json: any): RegisterClientAppResponse {
    return RegisterClientAppResponseFromJSONTyped(json, false);
}

export function RegisterClientAppResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterClientAppResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'appId': json['appId'] == null ? undefined : json['appId'],
        'appName': json['appName'] == null ? undefined : json['appName'],
        'key': json['key'] == null ? undefined : json['key'],
    };
}

export function RegisterClientAppResponseToJSON(json: any): RegisterClientAppResponse {
    return RegisterClientAppResponseToJSONTyped(json, false);
}

export function RegisterClientAppResponseToJSONTyped(value?: RegisterClientAppResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'appId': value['appId'],
        'appName': value['appName'],
        'key': value['key'],
    };
}

