/* tslint:disable */
/* eslint-disable */
/**
 * MailSender.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterClientAppRequest
 */
export interface RegisterClientAppRequest {
    /**
     * 
     * @type {string}
     * @memberof RegisterClientAppRequest
     */
    appId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RegisterClientAppRequest
     */
    appName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RegisterClientAppRequest
     */
    pass?: string | null;
}

/**
 * Check if a given object implements the RegisterClientAppRequest interface.
 */
export function instanceOfRegisterClientAppRequest(value: object): value is RegisterClientAppRequest {
    return true;
}

export function RegisterClientAppRequestFromJSON(json: any): RegisterClientAppRequest {
    return RegisterClientAppRequestFromJSONTyped(json, false);
}

export function RegisterClientAppRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterClientAppRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'appId': json['appId'] == null ? undefined : json['appId'],
        'appName': json['appName'] == null ? undefined : json['appName'],
        'pass': json['pass'] == null ? undefined : json['pass'],
    };
}

export function RegisterClientAppRequestToJSON(json: any): RegisterClientAppRequest {
    return RegisterClientAppRequestToJSONTyped(json, false);
}

export function RegisterClientAppRequestToJSONTyped(value?: RegisterClientAppRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'appId': value['appId'],
        'appName': value['appName'],
        'pass': value['pass'],
    };
}

