/* tslint:disable */
/* eslint-disable */
/**
 * MailSender.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendMailRequest
 */
export interface SendMailRequest {
    /**
     * 
     * @type {string}
     * @memberof SendMailRequest
     */
    to?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SendMailRequest
     */
    subject?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SendMailRequest
     */
    body?: string | null;
}

/**
 * Check if a given object implements the SendMailRequest interface.
 */
export function instanceOfSendMailRequest(value: object): value is SendMailRequest {
    return true;
}

export function SendMailRequestFromJSON(json: any): SendMailRequest {
    return SendMailRequestFromJSONTyped(json, false);
}

export function SendMailRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendMailRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'to': json['to'] == null ? undefined : json['to'],
        'subject': json['subject'] == null ? undefined : json['subject'],
        'body': json['body'] == null ? undefined : json['body'],
    };
}

export function SendMailRequestToJSON(json: any): SendMailRequest {
    return SendMailRequestToJSONTyped(json, false);
}

export function SendMailRequestToJSONTyped(value?: SendMailRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'to': value['to'],
        'subject': value['subject'],
        'body': value['body'],
    };
}

