/* tslint:disable */
/* eslint-disable */
/**
 * MailSender.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SendMailRequest } from './SendMailRequest';
import {
    SendMailRequestFromJSON,
    SendMailRequestFromJSONTyped,
    SendMailRequestToJSON,
    SendMailRequestToJSONTyped,
} from './SendMailRequest';

/**
 * 
 * @export
 * @interface SendMailResponse
 */
export interface SendMailResponse {
    /**
     * 
     * @type {string}
     * @memberof SendMailResponse
     */
    appId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SendMailResponse
     */
    appName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SendMailResponse
     */
    status?: string | null;
    /**
     * 
     * @type {SendMailRequest}
     * @memberof SendMailResponse
     */
    email?: SendMailRequest;
}

/**
 * Check if a given object implements the SendMailResponse interface.
 */
export function instanceOfSendMailResponse(value: object): value is SendMailResponse {
    return true;
}

export function SendMailResponseFromJSON(json: any): SendMailResponse {
    return SendMailResponseFromJSONTyped(json, false);
}

export function SendMailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendMailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'appId': json['appId'] == null ? undefined : json['appId'],
        'appName': json['appName'] == null ? undefined : json['appName'],
        'status': json['status'] == null ? undefined : json['status'],
        'email': json['email'] == null ? undefined : SendMailRequestFromJSON(json['email']),
    };
}

export function SendMailResponseToJSON(json: any): SendMailResponse {
    return SendMailResponseToJSONTyped(json, false);
}

export function SendMailResponseToJSONTyped(value?: SendMailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'appId': value['appId'],
        'appName': value['appName'],
        'status': value['status'],
        'email': SendMailRequestToJSON(value['email']),
    };
}

