/* tslint:disable */
/* eslint-disable */
/**
 * MailSender.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type RegisterClientAppRequest,
    RegisterClientAppRequestFromJSON,
    RegisterClientAppRequestToJSON,
} from '../models/RegisterClientAppRequest';
import {
    type RegisterClientAppResponse,
    RegisterClientAppResponseFromJSON,
    RegisterClientAppResponseToJSON,
} from '../models/RegisterClientAppResponse';

export interface ClientAppRegisterPostRequest {
    registerClientAppRequest?: RegisterClientAppRequest;
}

/**
 * 
 */
export class ClientAppApi extends runtime.BaseAPI {

    /**
     * Creates request options for clientAppRegisterPost without sending the request
     */
    async clientAppRegisterPostRequestOpts(requestParameters: ClientAppRegisterPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/client-app/register`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegisterClientAppRequestToJSON(requestParameters['registerClientAppRequest']),
        };
    }

    /**
     */
    async clientAppRegisterPostRaw(requestParameters: ClientAppRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RegisterClientAppResponse>> {
        const requestOptions = await this.clientAppRegisterPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RegisterClientAppResponseFromJSON(jsonValue));
    }

    /**
     */
    async clientAppRegisterPost(requestParameters: ClientAppRegisterPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RegisterClientAppResponse> {
        const response = await this.clientAppRegisterPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
