/* tslint:disable */
/* eslint-disable */
/**
 * MailSender.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type MailLog,
    MailLogFromJSON,
    MailLogToJSON,
} from '../models/MailLog';

export interface MailLogIdGetRequest {
    id: string;
}

/**
 * 
 */
export class MailLogApi extends runtime.BaseAPI {

    /**
     * Creates request options for mailLogGet without sending the request
     */
    async mailLogGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/mail-log`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async mailLogGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MailLog>>> {
        const requestOptions = await this.mailLogGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MailLogFromJSON));
    }

    /**
     */
    async mailLogGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MailLog>> {
        const response = await this.mailLogGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for mailLogIdGet without sending the request
     */
    async mailLogIdGetRequestOpts(requestParameters: MailLogIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling mailLogIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/mail-log/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async mailLogIdGetRaw(requestParameters: MailLogIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MailLog>> {
        const requestOptions = await this.mailLogIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MailLogFromJSON(jsonValue));
    }

    /**
     */
    async mailLogIdGet(requestParameters: MailLogIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MailLog> {
        const response = await this.mailLogIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
