/**
 * MailSender.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import { type RegisterClientAppRequest } from '../models/RegisterClientAppRequest';
import { type RegisterClientAppResponse } from '../models/RegisterClientAppResponse';
export interface ClientAppRegisterPostRequest {
    registerClientAppRequest?: RegisterClientAppRequest;
}
/**
 *
 */
export declare class ClientAppApi extends runtime.BaseAPI {
    /**
     * Creates request options for clientAppRegisterPost without sending the request
     */
    clientAppRegisterPostRequestOpts(requestParameters: ClientAppRegisterPostRequest): Promise<runtime.RequestOpts>;
    /**
     */
    clientAppRegisterPostRaw(requestParameters: ClientAppRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RegisterClientAppResponse>>;
    /**
     */
    clientAppRegisterPost(requestParameters?: ClientAppRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RegisterClientAppResponse>;
}
