/* tslint:disable */
/* eslint-disable */
/**
 * MailSender.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime.js';
import { SendMailRequestToJSON, } from '../models/SendMailRequest.js';
import { SendMailResponseFromJSON, } from '../models/SendMailResponse.js';
/**
 *
 */
export class MailApi extends runtime.BaseAPI {
    /**
     * Creates request options for mailSendPost without sending the request
     */
    async mailSendPostRequestOpts(requestParameters) {
        const queryParameters = {};
        const headerParameters = {};
        headerParameters['Content-Type'] = 'application/json';
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }
        let urlPath = `/mail/send`;
        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SendMailRequestToJSON(requestParameters['sendMailRequest']),
        };
    }
    /**
     */
    async mailSendPostRaw(requestParameters, initOverrides) {
        const requestOptions = await this.mailSendPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => SendMailResponseFromJSON(jsonValue));
    }
    /**
     */
    async mailSendPost(requestParameters = {}, initOverrides) {
        const response = await this.mailSendPostRaw(requestParameters, initOverrides);
        return await response.value();
    }
}
