/**
 * MailSender.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import { type MailLog } from '../models/MailLog';
export interface MailLogIdGetRequest {
    id: string;
}
/**
 *
 */
export declare class MailLogApi extends runtime.BaseAPI {
    /**
     * Creates request options for mailLogGet without sending the request
     */
    mailLogGetRequestOpts(): Promise<runtime.RequestOpts>;
    /**
     */
    mailLogGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MailLog>>>;
    /**
     */
    mailLogGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MailLog>>;
    /**
     * Creates request options for mailLogIdGet without sending the request
     */
    mailLogIdGetRequestOpts(requestParameters: MailLogIdGetRequest): Promise<runtime.RequestOpts>;
    /**
     */
    mailLogIdGetRaw(requestParameters: MailLogIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MailLog>>;
    /**
     */
    mailLogIdGet(requestParameters: MailLogIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MailLog>;
}
