/**
 * MailSender.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import { type SendMailRequest } from '../models/SendMailRequest';
import { type SendMailResponse } from '../models/SendMailResponse';
export interface MailSendPostRequest {
    sendMailRequest?: SendMailRequest;
}
/**
 *
 */
export declare class MailApi extends runtime.BaseAPI {
    /**
     * Creates request options for mailSendPost without sending the request
     */
    mailSendPostRequestOpts(requestParameters: MailSendPostRequest): Promise<runtime.RequestOpts>;
    /**
     */
    mailSendPostRaw(requestParameters: MailSendPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SendMailResponse>>;
    /**
     */
    mailSendPost(requestParameters?: MailSendPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SendMailResponse>;
}
