/* tslint:disable */
/* eslint-disable */
/**
 * MailSender.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the MailLog interface.
 */
export function instanceOfMailLog(value) {
    return true;
}
export function MailLogFromJSON(json) {
    return MailLogFromJSONTyped(json, false);
}
export function MailLogFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'id': json['id'] == null ? undefined : json['id'],
        'appId': json['appId'] == null ? undefined : json['appId'],
        'to': json['to'] == null ? undefined : json['to'],
        'subject': json['subject'] == null ? undefined : json['subject'],
        'body': json['body'] == null ? undefined : json['body'],
        'isSuccess': json['isSuccess'] == null ? undefined : json['isSuccess'],
        'errorMessage': json['errorMessage'] == null ? undefined : json['errorMessage'],
        'sentAt': json['sentAt'] == null ? undefined : (new Date(json['sentAt'])),
    };
}
export function MailLogToJSON(json) {
    return MailLogToJSONTyped(json, false);
}
export function MailLogToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'id': value['id'],
        'appId': value['appId'],
        'to': value['to'],
        'subject': value['subject'],
        'body': value['body'],
        'isSuccess': value['isSuccess'],
        'errorMessage': value['errorMessage'],
        'sentAt': value['sentAt'] == null ? value['sentAt'] : value['sentAt'].toISOString(),
    };
}
