/**
 * MailSender.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface MailLog
 */
export interface MailLog {
    /**
     *
     * @type {string}
     * @memberof MailLog
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof MailLog
     */
    appId?: string | null;
    /**
     *
     * @type {string}
     * @memberof MailLog
     */
    to?: string | null;
    /**
     *
     * @type {string}
     * @memberof MailLog
     */
    subject?: string | null;
    /**
     *
     * @type {string}
     * @memberof MailLog
     */
    body?: string | null;
    /**
     *
     * @type {boolean}
     * @memberof MailLog
     */
    isSuccess?: boolean;
    /**
     *
     * @type {string}
     * @memberof MailLog
     */
    errorMessage?: string | null;
    /**
     *
     * @type {Date}
     * @memberof MailLog
     */
    sentAt?: Date;
}
/**
 * Check if a given object implements the MailLog interface.
 */
export declare function instanceOfMailLog(value: object): value is MailLog;
export declare function MailLogFromJSON(json: any): MailLog;
export declare function MailLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailLog;
export declare function MailLogToJSON(json: any): MailLog;
export declare function MailLogToJSONTyped(value?: MailLog | null, ignoreDiscriminator?: boolean): any;
