/* tslint:disable */
/* eslint-disable */
/**
 * MailSender.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the RegisterClientAppResponse interface.
 */
export function instanceOfRegisterClientAppResponse(value) {
    return true;
}
export function RegisterClientAppResponseFromJSON(json) {
    return RegisterClientAppResponseFromJSONTyped(json, false);
}
export function RegisterClientAppResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'appId': json['appId'] == null ? undefined : json['appId'],
        'appName': json['appName'] == null ? undefined : json['appName'],
        'key': json['key'] == null ? undefined : json['key'],
    };
}
export function RegisterClientAppResponseToJSON(json) {
    return RegisterClientAppResponseToJSONTyped(json, false);
}
export function RegisterClientAppResponseToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'appId': value['appId'],
        'appName': value['appName'],
        'key': value['key'],
    };
}
