/* tslint:disable */
/* eslint-disable */
/**
 * MailSender.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the RegisterClientAppRequest interface.
 */
export function instanceOfRegisterClientAppRequest(value) {
    return true;
}
export function RegisterClientAppRequestFromJSON(json) {
    return RegisterClientAppRequestFromJSONTyped(json, false);
}
export function RegisterClientAppRequestFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'appId': json['appId'] == null ? undefined : json['appId'],
        'appName': json['appName'] == null ? undefined : json['appName'],
        'pass': json['pass'] == null ? undefined : json['pass'],
    };
}
export function RegisterClientAppRequestToJSON(json) {
    return RegisterClientAppRequestToJSONTyped(json, false);
}
export function RegisterClientAppRequestToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'appId': value['appId'],
        'appName': value['appName'],
        'pass': value['pass'],
    };
}
