/**
 * MailSender.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface RegisterClientAppRequest
 */
export interface RegisterClientAppRequest {
    /**
     *
     * @type {string}
     * @memberof RegisterClientAppRequest
     */
    appId?: string | null;
    /**
     *
     * @type {string}
     * @memberof RegisterClientAppRequest
     */
    appName?: string | null;
    /**
     *
     * @type {string}
     * @memberof RegisterClientAppRequest
     */
    pass?: string | null;
}
/**
 * Check if a given object implements the RegisterClientAppRequest interface.
 */
export declare function instanceOfRegisterClientAppRequest(value: object): value is RegisterClientAppRequest;
export declare function RegisterClientAppRequestFromJSON(json: any): RegisterClientAppRequest;
export declare function RegisterClientAppRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterClientAppRequest;
export declare function RegisterClientAppRequestToJSON(json: any): RegisterClientAppRequest;
export declare function RegisterClientAppRequestToJSONTyped(value?: RegisterClientAppRequest | null, ignoreDiscriminator?: boolean): any;
