/**
 * MailSender.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface RegisterClientAppResponse
 */
export interface RegisterClientAppResponse {
    /**
     *
     * @type {string}
     * @memberof RegisterClientAppResponse
     */
    appId?: string | null;
    /**
     *
     * @type {string}
     * @memberof RegisterClientAppResponse
     */
    appName?: string | null;
    /**
     *
     * @type {string}
     * @memberof RegisterClientAppResponse
     */
    key?: string | null;
}
/**
 * Check if a given object implements the RegisterClientAppResponse interface.
 */
export declare function instanceOfRegisterClientAppResponse(value: object): value is RegisterClientAppResponse;
export declare function RegisterClientAppResponseFromJSON(json: any): RegisterClientAppResponse;
export declare function RegisterClientAppResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterClientAppResponse;
export declare function RegisterClientAppResponseToJSON(json: any): RegisterClientAppResponse;
export declare function RegisterClientAppResponseToJSONTyped(value?: RegisterClientAppResponse | null, ignoreDiscriminator?: boolean): any;
