/**
 * MailSender.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface SendMailRequest
 */
export interface SendMailRequest {
    /**
     *
     * @type {string}
     * @memberof SendMailRequest
     */
    to?: string | null;
    /**
     *
     * @type {string}
     * @memberof SendMailRequest
     */
    subject?: string | null;
    /**
     *
     * @type {string}
     * @memberof SendMailRequest
     */
    body?: string | null;
}
/**
 * Check if a given object implements the SendMailRequest interface.
 */
export declare function instanceOfSendMailRequest(value: object): value is SendMailRequest;
export declare function SendMailRequestFromJSON(json: any): SendMailRequest;
export declare function SendMailRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendMailRequest;
export declare function SendMailRequestToJSON(json: any): SendMailRequest;
export declare function SendMailRequestToJSONTyped(value?: SendMailRequest | null, ignoreDiscriminator?: boolean): any;
