/* tslint:disable */
/* eslint-disable */
/**
 * MailSender.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SendMailRequestFromJSON, SendMailRequestToJSON, } from './SendMailRequest.js';
/**
 * Check if a given object implements the SendMailResponse interface.
 */
export function instanceOfSendMailResponse(value) {
    return true;
}
export function SendMailResponseFromJSON(json) {
    return SendMailResponseFromJSONTyped(json, false);
}
export function SendMailResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'appId': json['appId'] == null ? undefined : json['appId'],
        'appName': json['appName'] == null ? undefined : json['appName'],
        'status': json['status'] == null ? undefined : json['status'],
        'email': json['email'] == null ? undefined : SendMailRequestFromJSON(json['email']),
    };
}
export function SendMailResponseToJSON(json) {
    return SendMailResponseToJSONTyped(json, false);
}
export function SendMailResponseToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'appId': value['appId'],
        'appName': value['appName'],
        'status': value['status'],
        'email': SendMailRequestToJSON(value['email']),
    };
}
