/**
 * MailSender.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { SendMailRequest } from './SendMailRequest';
/**
 *
 * @export
 * @interface SendMailResponse
 */
export interface SendMailResponse {
    /**
     *
     * @type {string}
     * @memberof SendMailResponse
     */
    appId?: string | null;
    /**
     *
     * @type {string}
     * @memberof SendMailResponse
     */
    appName?: string | null;
    /**
     *
     * @type {string}
     * @memberof SendMailResponse
     */
    status?: string | null;
    /**
     *
     * @type {SendMailRequest}
     * @memberof SendMailResponse
     */
    email?: SendMailRequest;
}
/**
 * Check if a given object implements the SendMailResponse interface.
 */
export declare function instanceOfSendMailResponse(value: object): value is SendMailResponse;
export declare function SendMailResponseFromJSON(json: any): SendMailResponse;
export declare function SendMailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendMailResponse;
export declare function SendMailResponseToJSON(json: any): SendMailResponse;
export declare function SendMailResponseToJSONTyped(value?: SendMailResponse | null, ignoreDiscriminator?: boolean): any;
