/* tslint:disable */
/* eslint-disable */
/**
 * MailSender.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the SendMailRequest interface.
 */
export function instanceOfSendMailRequest(value) {
    return true;
}
export function SendMailRequestFromJSON(json) {
    return SendMailRequestFromJSONTyped(json, false);
}
export function SendMailRequestFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'to': json['to'] == null ? undefined : json['to'],
        'subject': json['subject'] == null ? undefined : json['subject'],
        'body': json['body'] == null ? undefined : json['body'],
    };
}
export function SendMailRequestToJSON(json) {
    return SendMailRequestToJSONTyped(json, false);
}
export function SendMailRequestToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'to': value['to'],
        'subject': value['subject'],
        'body': value['body'],
    };
}
